name: Cron Example

on:
  workflow_dispatch:

jobs:
 run-integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Setup nodeJs
      - name: Setup Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      #Install Yarn
      - name: Install Yarn
        run: npm install --global yarn

      # Install Dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      #Run tests
      - name: Run tests
        run: yarn tests
